version: 2.1
orbs:
  aws-ecs: circleci/aws-ecs@0.0.8
  aws-ecr: circleci/aws-ecr@6.1.0
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  one:
    docker:
      - image: circleci/python:3.7.1

    steps:
      - aws-cli/install
      - aws-cli/configure:
          aws-region: AWS_REGION
workflows:
  version: 2
  run-task:
    jobs:
      - one