# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/codingdiaz/circleci-feedback-testing
    steps:
      - checkout
#   test:
#     docker:
#       - image: circleci/golang:1.9
#     steps:
#       # specify any bash command here prefixed with `run: `
#       - run: echo "Hello World"
#       - run: exit 2
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build