version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/codingdiaz/circleci-feedback-testing
    steps:
      - checkout
      - run: make test
  test2:
    docker:
      - image: circleci/golang:1.12
    steps:
      - run: sleep 5
      - run: asdf
workflows:
  version: 2
  test:
    jobs:
      - test
      - test2