version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/codingdiaz/circleci-feedback-testing
    steps:
      - checkout
      - run: make test
      - run: curl https://releases.hashicorp.com/terraform/0.11.4/terraform_0.11.4_linux_amd64.zip && unzip terraform_0.11.4_linux_amd64.zip
workflows:
  version: 2
  test:
    jobs:
      - test