version: 2.1
orbs:
  aws-ecs: circleci/aws-ecs@0.0.8
  aws-cli: circleci/aws-cli@0.1.16
commands:
  run-task:
    description: |
      Starts a new task using the specified task definition and other parameters.
    parameters:
      cluster:
        description:
          "The name or ARN of the cluster on which to run the task."
        type: string
      task-definition:
        description: |
          "The family and revision (family:revision) or full ARN of the task
          definition to run. If a revision is not specified, the latest ACTIVE
          revision is used."
        type: string
      count:
        description: |
          "The number of instantiations of the specified task to place on your
          cluster. You can specify up to 10 tasks per call."
        type: integer
        default: 1
      started-by:
        description: |
          An optional tag specified when a task is started. For example, if
          you automatically trigger a task to run a batch process job, you
          could apply a unique identifier for that job to your task with the
          startedBy parameter. You can then identify which tasks belong to
          that job by filtering the results of a ListTasks  call with  the
          startedBy value. Up to 36 letters (uppercase and lowercase), num-
          bers, hyphens, and underscores are allowed.
        type: string
        default: ""
      group:
        description: |
          The name of the task group to associate with the task. The default
          value is the family name of the task definition (for example, family:my-family-name).
        type: string
        default: ""
      placement-constraints:
        description: |
          "An array of placement constraint objects to use for the task. You
          can specify up to 10 constraints per task (including constraints in
          the task definition and those specified at runtime). Expected format: type=string,field=string."
        type: string
        default: ""
      placement-strategy:
        description: |
          "The placement strategy objects to use for the task. You can  specify
          a maximum of five strategy rules per task. Expected format: type=string,field=string."
        type: string
        default: ""
      launch-type:
        description: |
          The launch type on which to run your task. For more information, see
          Amazon ECS Launch Types in  the  Amazon Elastic Container Service
          Developer Guide . Possible values EC2, FARGATE.
        type: enum
        enum: ["FARGATE", "EC2"]
        default: "FARGATE"
      platform-version:
        description: |
          "The platform version the task should run. A platform version is only
          specified for tasks using the Fargate launch type."
        type: string
        default: "LATEST"
      # network-configuration:
      #   description: |
      #     The network  configuration for the task. This parameter is required
      #     for task definitions that use the awsvpc network mode to receive
      #     their own elastic network interface, and it is not supported for
      #     other network modes. For more information, see Task Networking  in
      #     the Amazon Elastic Container Service Developer Guide .
      #   type: string
      #   default: ""
      subnet-ids:
        description: |
          "List of subnet ids"
        type: string
      security-group-ids:
        description: |
          "List of security group ids"
        type: string
        default: ""
      assign-public-ip:
        description: |
          "Assign a public IP or not"
        type: enum
        enum: ["ENABLED", "DISABLED"]
        default: "DISABLED"
      tags:
        description: |
          "The metadata that you apply to the task to help you categorize and
          organize them. Each tag consists of a key and an optional value,
          both of which you define. Expected format: key=string,value=string."
        type: string
        default: ""
      enable-ecs-managed-tags:
        description: |
          "Specifies whether to enable Amazon ECS managed tags for the task."
        type: boolean
        default: false
      propagate-tags:
        description: |
          "Specifies  whether to propagate the tags from the task definition to
          the task. If no value is specified, the  tags  are  not  propagated.
          Tags can only be propagated to the task during task creation. To add
          tags to a task after task creation, use the  TagResource API action."
        type: boolean
        default: false
    steps:
      - run:
          name: Run Task
          command: |
            if [ "<<parameters.launch-type>>" == "FARGATE" ]; then
                echo "Setting --launch-type"
                set -- "$@" --launch-type "<<parameters.launch-type>>"
            fi
            if [ ! -z "<<parameters.started-by>>" ]; then
                echo "Setting --started-by"
                set -- "$@" --started-by "<<parameters.started-by>>"
            fi
            if [ ! -z "<<parameters.group>>" ]; then
                echo "Setting --group"
                set -- "$@" --group "<<parameters.group>>"
            fi
            if [ ! -z "<<parameters.tags>>" ]; then
                echo "Setting --tags"
                set -- "$@" --tags "<<parameters.tags>>"
            fi
            if [ ! -z "<<parameters.placement-constraints>>" ]; then
                echo "Setting --placement-constraints"
                set -- "$@" --placement-constraints "<<parameters.placement-constraints>>"
            fi
            if [ ! -z "<<parameters.placement-strategy>>" ]; then
                echo "Setting --placement-strategy"
                set -- "$@" --placement-strategy "<<parameters.placement-strategy>>"
            fi
            if [ "<<parameters.enable-ecs-managed-tags>>" == "true" ]; then
                echo "Setting --enable-ecs-managed-tags"
                set -- "$@" --enable-ecs-managed-tags
            fi
            if [ "<<parameters.propagate-tags>>" == "true" ]; then
                echo "Setting --propagate-tags"
                set -- "$@" --propagate-tags "TASK_DEFINITION"
            fi

            echo $@

            aws ecs run-task \
              --cluster <<parameters.cluster>> \
              --task-definition <<parameters.task-definition>> \
              --count <<parameters.count>> \
              --platform-version <<parameters.platform-version>> \
              --network-configuration awsvpcConfiguration="{subnets=[<<parameters.subnet-ids>>],securityGroups=[<<parameters.security-group-ids>>],assignPublicIp=<<parameters.assign-public-ip>>}" \
              "$@" 
jobs:
  run-task:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run-task:
          task-definition: orb
          started-by: cdiaz
          cluster: testing
          launch-type: EC2
          subnet-ids: subnet-70ffa93b,subnet-bcc04b93
          enable-ecs-managed-tags: true
          propagate-tags: true
          tags: key=one,value=one
workflows:
  version: 2
  run-task:
    jobs:
      - run-task