version: 2.1
orbs:
  aws-ecs: circleci/aws-ecs@0.0.8
  aws-cli: circleci/aws-cli@0.1.16
jobs:
  run-task:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run: |
        aws ecs run-task 
          --cluster testing \
          --task-definition orb \
          --network-configuration awsvpcConfiguration="{subnets=[subnet-70ffa93b,subnet-bcc04b93],securityGroups=[],assignPublicIp=DISABLED}"  \
          --launch-type FARGATE
workflows:
  version: 2
  run-task:
    jobs:
      - one